name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    env: 
      ACTIONS_CACHE_URL: ""
    steps:
      # Checkout do repositório
      - name: Check out repository
        uses: actions/checkout@v3


      # Depuração antes de configurar o Python
      - name: Debug current Python version
        run: python --version || echo "Python not installed"

      # Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Depuração depois de configurar o Python
      - name: Verify Python version
        run: python --version

      # Limpar ou evitar cache de dependências
      - name: Clear cache (invalidate key)
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-pip

      # Instalar dependências
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt -f https://download.pytorch.org/whl/torch_stable.html

      # Executar testes
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest app/tests
